# Generated by Django 4.1.3 on 2023-01-23 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dms', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='folder',
            name='projectID',
            field=models.IntegerField(default=0),
        ),
    ]
