# Generated by Django 4.1.3 on 2023-02-19 11:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dms', '0004_remove_folder_projectid_folder_doku_container_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='FileCount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('folder_id', models.IntegerField(default=0)),
                ('projekt_id', models.IntegerField(default=0)),
                ('count', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.RemoveField(
            model_name='file',
            name='note',
        ),
        migrations.RemoveField(
            model_name='file',
            name='type',
        ),

        migrations.CreateModel(
            name='FileHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_by', models.CharField(default='admin', max_length=100)),
                ('update_by', models.CharField(default='admin', max_length=100)),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='creation time')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='update time')),
                ('is_delete', models.BooleanField(default=False, verbose_name='delete')),
                ('name', models.CharField(default='', max_length=200)),
                ('upload', models.FileField(upload_to='uploads/')),
                ('size', models.CharField(max_length=100)),
                ('version', models.IntegerField(default=0)),
                ('projekt_id', models.IntegerField(default=0)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dms.document')),
                ('folder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dms.folder')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
    ]
